# Generated by Django 5.2 on 2025-05-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_alter_ticket_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cargo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.IntegerField(),
        ),
    ]
