# Generated by Django 5.2 on 2025-05-01 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0005_alter_ticket_cargo_alter_ticket_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='cargo_num',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
