# Generated by Django 5.2 on 2025-05-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0007_alter_ticket_cargo_alter_ticket_seat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='cargo_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
