# Generated by Django 5.2 on 2025-05-02 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0008_alter_train_cargo_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created',
            new_name='created_at',
        ),
    ]
