# Generated by Django 5.2 on 2025-05-02 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0009_alter_order_options_rename_created_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='cargo_num',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='train',
            name='places_in_cargo',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
