# Generated by Django 5.2 on 2025-05-02 16:15

import station.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0010_alter_train_cargo_num_alter_train_places_in_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='image',
            field=models.ImageField(null=True, upload_to=station.models.station_image_file_path),
        ),
        migrations.AddField(
            model_name='train',
            name='image',
            field=models.ImageField(null=True, upload_to=station.models.train_image_file_path),
        ),
    ]
