# Generated by Django 5.2 on 2025-05-05 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0011_station_image_train_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='cargo_num',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='train',
            name='places_in_cargo',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
